import Header from "./components/main/header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-mainFont bg-bgColor w-full flex items-center justify-center flex-col">
        <Header />
        {children}
      </body>
    </html>
  );
}
